---
# local environment
spring:
  profiles: local

  # JPA(JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  # Data Source
  datasource:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
    open-in-view: false
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # H2 Web Console (H2ConsoleProperties)
  h2:
    console:
      path: /h2-console
      enabled: true
  # HTTP (HttpProperties)
  http:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
      enabled: true # Whether to enable http encoding support.
      force: true # Whether to force the encoding to the configured charset on HTTP requests and responses.

  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      enabled: true # Enable multipart uploads
      file-size-threshold: 2KB # Threshold after which files are written to disk.
      max-file-size: 200MB # Max file size.
      max-request-size: 215MB # Max Request Size

  # Customize spring mvc for full REST API.
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: debug # show sql statement
        type:
          descriptor:
            sql: trace # show sql values


---
# development environment
spring:
  profiles: development

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    datasource:
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: validate
      h2:
        console:
          enabled: true
    open-in-view: false

  # HTTP (HttpProperties)
  http:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
      enabled: true # Whether to enable http encoding support.
      force: true # Whether to force the encoding to the configured charset on HTTP requests and responses.

  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      enabled: true # Enable multipart uploads
      file-size-threshold: 2KB # Threshold after which files are written to disk.
      max-file-size: 200MB # Max file size.
      max-request-size: 215MB # Max Request Size

logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    max-history: 7
    max-size: 5MB
  level:
    root: info
    com:
      example:
        todolist:
          services: info
    org:
      springframework:
        web: error
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace # show sql values
